extends CharacterBody2D

@export var speed: float = 400  # Définir la vitesse de la balle
@export var raycast: RayCast2D



# Direction initiale du mouvement
var initial_direction: Vector2 = Vector2(1, 0)  # Exemple par défaut : vers la droite

func _ready() -> void:
	# Configurer la vitesse sur l'axe désiré
	velocity = initial_direction * speed  # Multiplie la direction initiale par la vitesse

func _physics_process(delta: float) -> void:
	move_and_collide(velocity * delta)
	if raycast.is_colliding():
		queue_free()

	
